version: "3.7"

services:
  mongo:
    image: "mongo:7.0.4"
    restart: always
    env_file:
      .env
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_NEWUSER_NAME: ${MONGO_NEWUSER_NAME}
      MONGO_NEWUSER_PASSWORD: ${MONGO_NEWUSER_PASSWORD}
      MONGO_INITDB_NAME: ${MONGO_INITDB_NAME}
      MONGO_INITDB_COL_USER: ${MONGO_INITDB_COL_USER}
      MONGO_INITDB_COL_APP: ${MONGO_INITDB_COL_APP}
    volumes:
      - ./storage/init/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
  server:
    env_file:
      .env
    environment:
      MONGO.DB_PORT: 27017
      MONGO.DB_USER: ${MONGO_NEWUSER_NAME}
      MONGO.DB_PASS: ${MONGO_NEWUSER_PASSWORD}
      MONGO.DB_AUTH_SOURCE: ${MONGO_INITDB_NAME}
      MONGO.DB_NAME: ${MONGO_INITDB_NAME}
      MONGO.DB_COL_USER: ${MONGO_INITDB_COL_USER}
      MONGO.DB_COL_APP: ${MONGO_INITDB_COL_APP}
      MONGO.DB_HOST: mongo
    build:
      context: ./
      dockerfile: ./build/Dockerfile
    ports:
      - ${PORT}:${INTERNAL_PORT}/tcp
    depends_on:
      - mongo