log_level: info
port: 44044
validator:
  email: ^(([^<>()\[\]\\.,;:\s@\"]+(\.[^<>()\[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$
  password: ^.{5,}$
  user_id: ^[1-9][0-9]*$
  app_id: ^[1-9][0-9]*$