log_level: info
port: 44044
validator:
  email: ^(([^<>()\[\]\\.,;:\s@\"]+(\.[^<>()\[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$
  password: ^.{5,}$
  user_id: ^[a-f\d]{24}$
  app_id: ^[a-f\d]{24}$
template:
  reg_link: localhost:1111/user/verification
mongo:
  db_con_format: mongodb
  db_host: localhost
  db_port: 27017
  db_user: ttt
  db_pass: ttt
  db_auth_source: testTT
  db_name: testTT
  db_col_user: user
  db_col_app: app
token_ttl: 30s
rabbitmq:
  scheme: amqp
  host: localhost
  port: 5672
  username: user1
  password: 123
  virtual_host: vhost1
  connection_name: testConn
  exchanger:
    name: test_exchanger
    type: direct
  binding:
    key: test-key
  queue:
    name: test-queue
  producer:
    count: 1
    rstrt_on_error: true 
    cancel_on_error: false
    tts: 500s
    send_await_time: 100s