# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:

  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.1'

    - name: Install dependencies
      run: go mod tidy

    - name: Build
      run: CGO_ENABLED=0 GOOS=linux go build -o serverMain ./cmd/server/

    - name: Unit tests
      run: go test `go list ./... | grep -v ./tests`

    - name: E2E tests
      run: go test ./tests
